In [6]:
import pandas as pd

In [10]:
import urllib.request

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip"

urllib.request.urlretrieve(url, "smsspamcollection.zip")

print("Download complete!")

Download complete!

In [11]:
import zipfile

with zipfile.ZipFile("smsspamcollection.zip", "r") as zip_ref:
    zip_ref.extractall(".")

print("Extracted!")

Extracted!

In [12]:
import os

print(os.path.getsize("SMSSpamCollection") / 1024, "KB")

466.7060546875 KB

In [13]:
import pandas as pd

df = pd.read_csv(
    "SMSSpamCollection",
    sep="\t",
    header=None,
    names=["label", "message"]
)

In [14]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
import pandas as pd

df = pd.read_csv(
    "SMSSpamCollection",
    sep="\t",
    header=None,
    names=["label", "message"]
)

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Shape: (5572, 2)

Columns:
Index(['label', 'message'], dtype='str')

Data Types:
label      str
message    str
dtype: object

In [17]:
df[df["label"] == "ham"].head(5)

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
6   ham  Even my brother is not like to speak with me. ...

In [18]:
df[df["label"] == "spam"].head(5)

   label                                            message
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
5   spam  FreeMsg Hey there darling it's been 3 week's n...
8   spam  WINNER!! As a valued network customer you have...
9   spam  Had your mobile 11 months or more? U R entitle...
11  spam  SIX chances to win CASH! From 100 to 20,000 po...

In [19]:
df["label"] == "spam"

0       False
1       False
2        True
3       False
4       False
        ...
5567     True
5568    False
5569    False
5570    False
5571    False
Name: label, Length: 5572, dtype: bool

In [20]:
df["message_length"] = df["message"].str.len()

df[["label", "message", "message_length"]].head()

  label                                            message  message_length
0   ham  Go until jurong point, crazy.. Available only ...             111
1   ham                      Ok lar... Joking wif u oni...              29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...             155
3   ham  U dun say so early hor... U c already then say...              49
4   ham  Nah I don't think he goes to usf, he lives aro...              61

In [21]:
df.groupby("label")["message_length"].mean()

label
ham      71.482487
spam    138.670683
Name: message_length, dtype: float64

In [22]:
df["clean_message"] = df["message"].str.lower()

df[["message", "clean_message"]].head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ..."
1,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...
4,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro..."

In [23]:
import string

df["clean_message"] = df["clean_message"].str.translate(
    str.maketrans("", "", string.punctuation)
)

df[["message", "clean_message"]].head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...

In [24]:
df.head()

,label,message,message_length,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",111,go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,29,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,155,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,49,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",61,nah i dont think he goes to usf he lives aroun...

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df["clean_message"])

In [27]:
tfidf = TfidfVectorizer()

In [28]:
X = tfidf.fit_transform(df["clean_message"])

In [29]:
print(X.shape)

(5572, 9544)

In [30]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 72798 stored elements and shape (5572, 9544)>

In [32]:
from sklearn.model_selection import train_test_split

In [34]:
y = df["label"]

In [35]:
print(y.head())

0     ham
1     ham
2    spam
3     ham
4     ham
Name: label, dtype: str

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [37]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (4457, 9544)
X_test: (1115, 9544)
y_train: (4457,)
y_test: (1115,)

In [38]:
from sklearn.naive_bayes import MultinomialNB

In [39]:
model = MultinomialNB()

In [40]:
model.fit(X_train, y_train)

MultinomialNB()

In [41]:
print("Model training complete!")

Model training complete!

In [42]:
y_pred = model.predict(X_test)

In [43]:
print(y_pred[:10])

['ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham']

In [44]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.95695067264574

In [45]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[966   0]
 [ 48 101]]

In [46]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.95      1.00      0.98       966
        spam       1.00      0.68      0.81       149

    accuracy                           0.96      1115
   macro avg       0.98      0.84      0.89      1115
weighted avg       0.96      0.96      0.95      1115

In [47]:
new_message = ["Congratulations! You have won a free prize. Click now!"]

In [48]:
new_message_tfidf = tfidf.transform(new_message)

In [49]:
prediction = model.predict(new_message_tfidf)

print(prediction)

['spam']

In [50]:
if prediction[0] == "spam":
    print("Prediction: SPAM 🚨")
else:
    print("Prediction: NOT SPAM ✅")

Prediction: SPAM 🚨

In [51]:
import joblib

In [52]:
joblib.dump(model, "spam_model.pkl")

['spam_model.pkl']

In [53]:
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [1]:
pip install streamlit

Requirement already satisfied: streamlit in c:\Users\priya\anaconda3\Lib\site-packages (1.58.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: click<9,>=7.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (2.4.6)
Requirement already satisfied: packaging>=20 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (3.0.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (12.3.0)
Requirement already satisfied: protobuf<8,>=3.20 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (6.33.5)
Requirement already satisfied: pyarrow>=7.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette>=0.40.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (0.40.0)
Requirement already satisfied: httptools>=0.6.3 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (4.12.1)
Requirement already satisfied: python-multipart>=0.0.10 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\Users\priya\anaconda3\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\Users\priya\anaconda3\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\Users\priya\anaconda3\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.27.1 in c:\Users\priya\anaconda3\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.23.0)
Requirement already satisfied: colorama in c:\Users\priya\anaconda3\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\Users\priya\anaconda3\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\Users\priya\anaconda3\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\priya\anaconda3\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\priya\anaconda3\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\priya\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\priya\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\priya\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\priya\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\priya\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\priya\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\priya\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\Users\priya\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\Users\priya\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in c:\Users\priya\anaconda3\Lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\priya\anaconda3\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
df["clean_message"]

NameError: name 'df' is not defined

In [3]:
import pandas as pd
import string

df = pd.read_csv(
    "SMSSpamCollection",
    sep="\t",
    header=None,
    names=["label", "message"]
)

df["clean_message"] = df["message"].str.lower()

df["clean_message"] = df["clean_message"].str.translate(
    str.maketrans("", "", string.punctuation)
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (5572, 3)

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
import joblib

X_text = df["clean_message"]
y = df["label"]

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

tfidf = TfidfVectorizer()

X_train = tfidf.fit_transform(X_train_text)
X_test = tfidf.transform(X_test_text)

model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

joblib.dump(model, "spam_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("\nModel and TF-IDF vectorizer saved successfully!")

Accuracy: 0.9524663677130045

Classification Report:
              precision    recall  f1-score   support

         ham       0.95      1.00      0.97       966
        spam       1.00      0.64      0.78       149

    accuracy                           0.95      1115
   macro avg       0.97      0.82      0.88      1115
weighted avg       0.95      0.95      0.95      1115


Model and TF-IDF vectorizer saved successfully!

In [ ]:
new_message = ["Congratulations, You have won a free prize. Click now!"]

new_message_tfidf = tfidf.transform(new_message)

prediction = model.predict(new_message_tfidf)
probability = model.predict_proba(new_message_tfidf)

print("Prediction:", prediction[0])
print("Spam Probability:", probability[0][1] * 100)

Prediction: spam
Spam Probability: 83.35170809835608

In [6]:
new_message = ["Hey, are you coming to college today?"]

new_message_tfidf = tfidf.transform(new_message)

prediction = model.predict(new_message_tfidf)
probability = model.predict_proba(new_message_tfidf)

print("Prediction:", prediction[0])
print("Spam Probability:", probability[0][1] * 100)

Prediction: ham
Spam Probability: 0.3395311677382218